version: 0.2
phases:
  install:
    commands:
      - pip install pandas==2.2.2 -t freshmart-data-pipeline/lambdas/csv_reader/package/ --platform manylinux2014_x86_64 --only-binary=:all:
      - pip install pandas==2.2.2 -t freshmart-data-pipeline/lambdas/transformer/package/ --platform manylinux2014_x86_64 --only-binary=:all:
  build:
    commands:
      - mkdir -p artifacts
      - cp freshmart-data-pipeline/lambdas/csv_reader/lambda_function.py freshmart-data-pipeline/lambdas/csv_reader/package/
      - cd freshmart-data-pipeline/lambdas/csv_reader/package && zip -r ../../../../artifacts/csv_reader.zip . && cd ../../../..
      - zip -j artifacts/orchestrator.zip freshmart-data-pipeline/lambdas/orchestrator/lambda_function.py
      - cp freshmart-data-pipeline/lambdas/transformer/lambda_function.py freshmart-data-pipeline/lambdas/transformer/package/
      - cd freshmart-data-pipeline/lambdas/transformer/package && zip -r ../../../../artifacts/transformer.zip . && cd ../../../..
  post_build:
    commands:
      - chmod +x freshmart-data-pipeline/scripts/deploy.sh
      - freshmart-data-pipeline/scripts/deploy.sh csv_reader_lambda artifacts/csv_reader.zip
      - freshmart-data-pipeline/scripts/deploy.sh pipeline_orchestrator artifacts/orchestrator.zip
      - freshmart-data-pipeline/scripts/deploy.sh data_transformer_worker artifacts/transformer.zip
